"use client";

import { useState } from "react";
import { Calculator, FileSearch, Landmark, Scale } from "lucide-react";
import { enrollAssessment, evaluateCertificate, saveIssDeclaration, saveServiceActivity, saveTaxParameter, saveTaxServiceRequest } from "./actions";

type Props = { taxes: { id: string; name: string }[]; taxpayers: { id: string; name: string }[]; processes: { id: string; protocolNumber: string; status: string }[]; documents: { id: string; title: string }[]; activities: { id: string; name: string; rate: string }[]; assessments: { id: string; label: string }[]; parameters: { id: string; label: string }[]; requests: { id: string; serviceType: string; status: string; taxpayer: string; process: string }[]; evaluations: { id: string; result: string; pendingCount: number; taxpayer: string; date: string }[] };

export default function OperacoesTributariasClient({ taxes, taxpayers, processes, documents, activities, assessments, parameters, requests, evaluations }: Props) {
  const [notice, setNotice] = useState<string>();
  const [parameter, setParameter] = useState({ taxId: taxes[0]?.id ?? "", code: "", name: "", calculationType: "ALIQUOTA", configuration: "{}", effectiveFrom: new Date().toISOString().slice(0, 10) });
  const [request, setRequest] = useState({ serviceType: "ITBI", taxpayerId: taxpayers[0]?.id ?? "", processId: processes[0]?.id ?? "", documentId: "", assessmentId: "", notes: "" });
  const [iss, setIss] = useState({ taxpayerId: taxpayers[0]?.id ?? "", activityId: activities[0]?.id ?? "", competence: new Date().toISOString().slice(0, 10), serviceValue: 0, deductionValue: 0 });
  const [activity, setActivity] = useState({ taxId: taxes[0]?.id ?? "", code: "", name: "", issRate: 0 });
  const done = (result: { error?: string }, success: string) => setNotice(result.error ?? success);

  return <div className="space-y-6">
    <div className="flex gap-3"><Scale className="w-7 h-7 text-emerald-700 mt-1" /><div><h1 className="text-2xl font-bold text-slate-900">Operacoes Tributarias Internas</h1><p className="text-sm text-slate-500">Fundacoes configuraveis e auditaveis. Nao emite documento fiscal, CDA, certidao ou alvara oficial.</p></div></div>
    {notice && <p className="rounded-lg bg-amber-50 border border-amber-200 text-amber-900 p-3 text-sm">{notice}</p>}
    <div className="grid xl:grid-cols-2 gap-6">
      <form onSubmit={async (event) => { event.preventDefault(); done(await saveTaxParameter(parameter), "Parametro interno salvo."); }} className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold flex gap-2"><Calculator className="w-5 h-5 text-emerald-700" />IPTU, taxas e parametros</h2><select required value={parameter.taxId} onChange={(event) => setParameter({ ...parameter, taxId: event.target.value })} className="w-full border rounded p-2 text-sm">{taxes.map((tax) => <option key={tax.id} value={tax.id}>{tax.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input required placeholder="Codigo" value={parameter.code} onChange={(event) => setParameter({ ...parameter, code: event.target.value })} className="border rounded p-2 text-sm" /><input required placeholder="Nome" value={parameter.name} onChange={(event) => setParameter({ ...parameter, name: event.target.value })} className="border rounded p-2 text-sm" /></div><input required placeholder="Tipo de calculo" value={parameter.calculationType} onChange={(event) => setParameter({ ...parameter, calculationType: event.target.value })} className="w-full border rounded p-2 text-sm" /><textarea required value={parameter.configuration} onChange={(event) => setParameter({ ...parameter, configuration: event.target.value })} className="w-full border rounded p-2 text-sm" rows={3} aria-label="Configuracao JSON" /><input type="date" required value={parameter.effectiveFrom} onChange={(event) => setParameter({ ...parameter, effectiveFrom: event.target.value })} className="border rounded p-2 text-sm" /><button className="bg-emerald-700 text-white rounded px-3 py-2 text-sm font-semibold">Salvar configuracao</button><p className="text-xs text-slate-500">Use para PGV, aliquotas, isencoes e taxas apos validacao normativa.</p></form>
      <form onSubmit={async (event) => { event.preventDefault(); done(await saveTaxServiceRequest(request), "Solicitacao interna vinculada ao Processo e GED."); }} className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold flex gap-2"><FileSearch className="w-5 h-5 text-emerald-700" />ITBI e alvara via Processo/GED</h2><select value={request.serviceType} onChange={(event) => setRequest({ ...request, serviceType: event.target.value })} className="w-full border rounded p-2 text-sm"><option value="ITBI">ITBI</option><option value="ALVARA">Alvara</option></select><select required value={request.taxpayerId} onChange={(event) => setRequest({ ...request, taxpayerId: event.target.value })} className="w-full border rounded p-2 text-sm">{taxpayers.map((taxpayer) => <option key={taxpayer.id} value={taxpayer.id}>{taxpayer.name}</option>)}</select><select required value={request.processId} onChange={(event) => setRequest({ ...request, processId: event.target.value })} className="w-full border rounded p-2 text-sm"><option value="">Processo do Modulo 3</option>{processes.map((process) => <option key={process.id} value={process.id}>{process.protocolNumber} - {process.status}</option>)}</select><select value={request.documentId} onChange={(event) => setRequest({ ...request, documentId: event.target.value })} className="w-full border rounded p-2 text-sm"><option value="">Documento GED opcional</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.title}</option>)}</select><textarea placeholder="Observacoes internas" value={request.notes} onChange={(event) => setRequest({ ...request, notes: event.target.value })} className="w-full border rounded p-2 text-sm" rows={2} /><button className="bg-emerald-700 text-white rounded px-3 py-2 text-sm font-semibold">Registrar fluxo interno</button></form>
      <form onSubmit={async (event) => { event.preventDefault(); done(await saveIssDeclaration(iss), "ISS apurado internamente com base na atividade configurada."); }} className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold flex gap-2"><Landmark className="w-5 h-5 text-emerald-700" />ISS e catalogo de servicos</h2><select required value={iss.taxpayerId} onChange={(event) => setIss({ ...iss, taxpayerId: event.target.value })} className="w-full border rounded p-2 text-sm">{taxpayers.map((taxpayer) => <option key={taxpayer.id} value={taxpayer.id}>{taxpayer.name}</option>)}</select><select required value={iss.activityId} onChange={(event) => setIss({ ...iss, activityId: event.target.value })} className="w-full border rounded p-2 text-sm">{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.name} - {activity.rate}%</option>)}</select><div className="grid grid-cols-3 gap-2"><input type="date" required value={iss.competence} onChange={(event) => setIss({ ...iss, competence: event.target.value })} className="border rounded p-2 text-sm" /><input type="number" min="0.01" step="0.01" placeholder="Servicos" value={iss.serviceValue || ""} onChange={(event) => setIss({ ...iss, serviceValue: Number(event.target.value) })} className="border rounded p-2 text-sm" /><input type="number" min="0" step="0.01" placeholder="Deducoes" value={iss.deductionValue || ""} onChange={(event) => setIss({ ...iss, deductionValue: Number(event.target.value) })} className="border rounded p-2 text-sm" /></div><button className="bg-emerald-700 text-white rounded px-3 py-2 text-sm font-semibold">Apurar internamente</button></form>
      <form onSubmit={async (event) => { event.preventDefault(); done(await saveServiceActivity(activity), "Atividade e aliquota ISS internas salvas."); }} className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold">Nova atividade de servico ISS</h2><select required value={activity.taxId} onChange={(event) => setActivity({ ...activity, taxId: event.target.value })} className="w-full border rounded p-2 text-sm">{taxes.map((tax) => <option key={tax.id} value={tax.id}>{tax.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input required placeholder="Codigo" value={activity.code} onChange={(event) => setActivity({ ...activity, code: event.target.value })} className="border rounded p-2 text-sm" /><input required placeholder="Nome" value={activity.name} onChange={(event) => setActivity({ ...activity, name: event.target.value })} className="border rounded p-2 text-sm" /></div><input required type="number" min="0" step="0.000001" placeholder="Aliquota (%)" value={activity.issRate || ""} onChange={(event) => setActivity({ ...activity, issRate: Number(event.target.value) })} className="w-full border rounded p-2 text-sm" /><button className="bg-emerald-700 text-white rounded px-3 py-2 text-sm font-semibold">Salvar atividade</button></form>
      <section className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold">Divida ativa e situacao fiscal</h2><select onChange={async (event) => { if (event.target.value) done(await enrollAssessment(event.target.value), "Lancamento incluido como base pendente de validacao para divida ativa."); }} className="w-full border rounded p-2 text-sm" defaultValue=""><option value="">Enviar lancamento pendente para base de divida</option>{assessments.map((assessment) => <option key={assessment.id} value={assessment.id}>{assessment.label}</option>)}</select><select onChange={async (event) => { if (event.target.value) done(await evaluateCertificate(event.target.value), "Situacao fiscal avaliada internamente, sem emissao de certidao."); }} className="w-full border rounded p-2 text-sm" defaultValue=""><option value="">Avaliar situacao de contribuinte</option>{taxpayers.map((taxpayer) => <option key={taxpayer.id} value={taxpayer.id}>{taxpayer.name}</option>)}</select><p className="text-xs text-slate-500">Parcelamento, CDA e certidoes exigem validacao juridica/fiscal antes de qualquer efeito externo.</p></section>
    </div>
    <div className="grid lg:grid-cols-3 gap-4 text-sm"><section className="bg-white border rounded-xl p-4"><h2 className="font-bold mb-2">Parametros recentes</h2>{parameters.map((item) => <p key={item.id} className="py-1 text-slate-600">{item.label}</p>)}{!parameters.length && <p className="text-slate-500">Sem parametros internos.</p>}</section><section className="bg-white border rounded-xl p-4"><h2 className="font-bold mb-2">Fluxos solicitados</h2>{requests.map((item) => <p key={item.id} className="py-1 text-slate-600">{item.serviceType}: {item.taxpayer} · {item.process} · {item.status}</p>)}{!requests.length && <p className="text-slate-500">Sem fluxos internos.</p>}</section><section className="bg-white border rounded-xl p-4"><h2 className="font-bold mb-2">Avaliacoes fiscais</h2>{evaluations.map((item) => <p key={item.id} className="py-1 text-slate-600">{item.taxpayer}: {item.result} ({item.pendingCount})</p>)}{!evaluations.length && <p className="text-slate-500">Sem avaliacoes.</p>}</section></div>
  </div>;
}
