import Link from "next/link";
import { notFound } from "next/navigation";
import { getAttendanceContext, ticketScope } from "@/lib/attendance/access";
import DocumentUpload from "../../DocumentUpload";
import { addTicketInteraction, assumeTicket, assignTicket, concludeTicket, createProcessFromTicket, forwardTicket, reopenTicket, resolveTicket } from "../../actions";

export const dynamic = "force-dynamic";

export default async function TicketDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const context = await getAttendanceContext();
  const ticket = await context.prisma.ticket.findFirst({
    where: { AND: [{ id }, ticketScope(context)] },
    include: {
      person: true, company: true, channel: true, department: true, assignee: true, serviceSubject: true, resolvedBy: true, concludedBy: true, process: true,
      interactions: { include: { employee: { select: { name: true } } }, orderBy: { createdAt: "asc" } },
      movements: { include: { fromDepartment: { select: { name: true } }, toDepartment: { select: { name: true } }, employee: { select: { name: true } } }, orderBy: { createdAt: "asc" } },
      documents: { include: { document: true }, orderBy: { createdAt: "desc" } },
      auditLogs: { include: { user: { select: { nome: true } } }, orderBy: { createdAt: "desc" }, take: 50 },
    },
  });
  if (!ticket) notFound();
  await context.prisma.ticketAuditLog.create({ data: { ticketId: id, userId: context.user.id, employeeId: context.user.employeeId, action: "VIEWED" } });
  const [departments, employees, processTypes] = await Promise.all([
    context.prisma.department.findMany({ where: { isActive: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
    ticket.departmentId ? context.prisma.employee.findMany({ where: { isActive: true, departmentId: ticket.departmentId }, select: { id: true, name: true }, orderBy: { name: "asc" } }) : [],
    context.prisma.processType.findMany({ where: { isActive: true }, include: { subjects: { where: { isActive: true } } }, orderBy: { name: "asc" } }),
  ]);
  const closed = ["Resolvido", "Concluído", "Cancelado"].includes(ticket.status);
  const requester = ticket.isAnonymous ? "Anônimo" : ticket.person ? `${ticket.person.fullName} · CPF ${ticket.person.cpf}` : ticket.company ? `${ticket.company.corporateName} · CNPJ ${ticket.company.cnpj}` : "Não informado";
  return <div className="max-w-6xl mx-auto space-y-6">
    <header className="flex flex-wrap justify-between gap-4"><div><Link href="/atendimento/central" className="text-sm text-violet-700">Voltar para a Central</Link><h1 className="text-2xl font-bold mt-2">{ticket.ticketNumber}</h1><p className="text-slate-500">{ticket.subject}</p></div><div className="text-right"><strong>{ticket.status}</strong><p className="text-sm text-slate-500">Prioridade: {ticket.priority}</p></div></header>
    <div className="grid lg:grid-cols-3 gap-6"><section className="lg:col-span-2 bg-white border rounded-xl p-5 space-y-5"><div className="grid sm:grid-cols-2 gap-4 text-sm"><p><span className="text-slate-500 block">Solicitante</span>{requester}</p><p><span className="text-slate-500 block">Canal</span>{ticket.channel.name}</p><p><span className="text-slate-500 block">Setor atual</span>{ticket.department?.name || "Triagem pendente"}</p><p><span className="text-slate-500 block">Responsável</span>{ticket.assignee?.name || "Não assumido"}</p><p><span className="text-slate-500 block">Prazo/SLA</span>{ticket.dueAt?.toLocaleString("pt-BR") || "Não definido"}</p><p><span className="text-slate-500 block">Assunto parametrizado</span>{ticket.serviceSubject?.name || "Não classificado"}</p></div><div><h2 className="font-semibold">Descrição</h2><p className="whitespace-pre-wrap text-slate-700 mt-2">{ticket.description}</p></div>{ticket.solution && <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4"><h2 className="font-semibold text-emerald-900">Solução registrada</h2><p className="whitespace-pre-wrap text-emerald-800 mt-1">{ticket.solution}</p></div>}</section>
      <aside className="space-y-4"><form action={assumeTicket} className="bg-white border rounded-xl p-4"><input type="hidden" name="ticketId" value={ticket.id} /><button disabled={closed} className="w-full px-3 py-2 bg-violet-600 text-white rounded-lg disabled:opacity-50">Assumir chamado</button></form>{context.attendanceAccess.isManager && <form action={assignTicket} className="bg-white border rounded-xl p-4 space-y-2"><input type="hidden" name="ticketId" value={ticket.id} /><label className="text-sm font-semibold">Atribuir responsável</label><select name="assigneeId" required className="w-full p-2 border rounded-lg"><option value="">Selecione</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><button className="w-full p-2 border rounded-lg text-sm">Atribuir</button></form>}<form action={forwardTicket} className="bg-white border rounded-xl p-4 space-y-2"><input type="hidden" name="ticketId" value={ticket.id} /><label className="text-sm font-semibold">Encaminhar</label><select name="toDepartmentId" required className="w-full p-2 border rounded-lg"><option value="">Setor de destino</option>{departments.filter((department) => department.id !== ticket.departmentId).map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><textarea name="reason" required rows={2} placeholder="Motivo" className="w-full p-2 border rounded-lg" /><button disabled={closed} className="w-full p-2 border rounded-lg text-sm disabled:opacity-50">Encaminhar</button></form></aside></div>
    <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5 space-y-4"><h2 className="font-bold">Interações e histórico</h2><form action={addTicketInteraction} className="space-y-2 border-b pb-4"><input type="hidden" name="ticketId" value={ticket.id} /><div className="flex gap-2"><select name="type" className="p-2 border rounded-lg text-sm"><option>Comentário</option><option>Resposta</option><option>Solicitação de Informação</option></select><button className="px-3 py-2 bg-slate-800 text-white rounded-lg text-sm">Registrar</button></div><textarea name="message" required rows={3} placeholder="Descreva a movimentação ou providência." className="w-full p-2 border rounded-lg" /></form>{ticket.interactions.map((interaction) => <div key={interaction.id} className="border-l-2 border-violet-300 pl-3"><p className="text-sm font-semibold">{interaction.type} · {interaction.employee?.name || "Sistema"}</p><p className="text-sm text-slate-700 whitespace-pre-wrap">{interaction.message}</p><small className="text-slate-500">{interaction.createdAt.toLocaleString("pt-BR")}</small></div>)}</section>
      <section className="space-y-4"><form action={resolveTicket} className="bg-white border rounded-xl p-5 space-y-2"><input type="hidden" name="ticketId" value={ticket.id} /><h2 className="font-bold">Resolver</h2><textarea name="solution" required rows={3} defaultValue={ticket.solution || ""} className="w-full p-2 border rounded-lg" /><button disabled={closed} className="px-3 py-2 bg-emerald-600 text-white rounded-lg text-sm disabled:opacity-50">Registrar solução</button></form><form action={concludeTicket} className="bg-white border rounded-xl p-5 flex justify-between items-center"><span className="text-sm">Concluir após a solução registrada.</span><input type="hidden" name="ticketId" value={ticket.id} /><button disabled={ticket.status !== "Resolvido"} className="px-3 py-2 bg-slate-800 text-white rounded-lg text-sm disabled:opacity-50">Concluir</button></form>{closed && <form action={reopenTicket} className="bg-white border rounded-xl p-5 space-y-2"><input type="hidden" name="ticketId" value={ticket.id} /><h2 className="font-bold">Reabrir</h2><input name="reason" required placeholder="Motivo da reabertura" className="w-full p-2 border rounded-lg" /><button className="px-3 py-2 border rounded-lg text-sm">Reabrir chamado</button></form>}</section></div>
    <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold">Documentos GED</h2><DocumentUpload entityType="ticket" entityId={ticket.id} />{ticket.documents.map((link) => <a key={link.id} href={`/api/download?url=${encodeURIComponent(link.document.fileUrl)}`} target="_blank" rel="noreferrer" className="block text-sm text-violet-700">{link.document.title}</a>)}</section><section className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold">Processo relacionado</h2>{ticket.process ? <Link href={`/protocolos/processos/${ticket.process.id}`} className="font-semibold text-emerald-700">{ticket.process.protocolNumber} · {ticket.process.status}</Link> : <form action={createProcessFromTicket} className="space-y-2"><input type="hidden" name="ticketId" value={ticket.id} /><select name="processTypeId" required className="w-full p-2 border rounded-lg"><option value="">Tipo de processo</option>{processTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><select name="subjectId" required className="w-full p-2 border rounded-lg"><option value="">Assunto do processo</option>{processTypes.flatMap((type) => type.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name} ({type.name})</option>))}</select><select name="initialDepartmentId" className="w-full p-2 border rounded-lg"><option value="">Setor configurado</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><select name="priority" className="w-full p-2 border rounded-lg"><option value="">Prioridade configurada</option><option>Normal</option><option>Alta</option><option>Urgente</option></select><button className="px-3 py-2 bg-emerald-600 text-white rounded-lg text-sm">Gerar protocolo</button></form>}</section></div>
    <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5"><h2 className="font-bold mb-3">Encaminhamentos</h2>{ticket.movements.map((movement) => <p key={movement.id} className="text-sm mb-3"><strong>{movement.fromDepartment?.name || "Abertura"} → {movement.toDepartment.name}</strong><br />{movement.reason}<br /><small className="text-slate-500">{movement.employee.name} · {movement.createdAt.toLocaleString("pt-BR")}</small></p>) || <p>Sem encaminhamentos.</p>}</section>{context.attendanceAccess.isManager && <section className="bg-white border rounded-xl p-5"><h2 className="font-bold mb-3">Auditoria</h2>{ticket.auditLogs.map((log) => <p key={log.id} className="text-sm mb-2">{log.action} · {log.user.nome} · {log.createdAt.toLocaleString("pt-BR")}</p>)}</section>}</div>
  </div>;
}
